### ISSUE TITLE
Android issue with decimals

### ISSUE THREAD

**Issue by javiholcman** [AlejandroRuiz/PayPal.Forms#5] opened 2016-06-10 17:31 UTC
When I pay with a decimal number, the payment couldn't be finished. But if I pay a rounded number (like 10.00) it works fine.

Console logs: 

[paypal.sdk] request failure with http statusCode:400,exception:Bad Request
[paypal.sdk] request failed with server response:{"name":"VALIDATION_ERROR","details":[{"field":"transactions.item_list.items","issue":"Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/#VALIDATION_ERROR","debug_id":"b35d95054f98c"}
[paypal.sdk] 
[paypal.sdk] VALIDATION_ERROR

**Comment by AlejandroRuiz** [comment] 2016-06-22 23:33
@javiholcman it will be great if you can give me more details about this issue ie. Android OS version, device language and also which PayPal.Forms versions are you using?

**Comment by javiholcman** [comment] 2016-06-23 12:38
@AlejandroRuiz I am using a Spanish language on a S6 device of Genymotion and the 2.0.4 version of Paypal.Forms.

**Comment by fcogutierrez** [comment] 2016-06-27 08:28
I have exactly the same error from a Samsung Galaxy Tab 2.

**Comment by fcogutierrez** [comment] 2016-06-28 13:24
This is the array that I am sending:

![image](https://cloud.githubusercontent.com/assets/8028313/16416842/5f906870-3d44-11e6-9a36-32db9e19fc4e.png)

And here is the output...

_06-24 15:22:12.550 D/SRIB_DCS(29308): log_dcs ThreadedRenderer::initialize entered! 
06-24 15:22:12.550 D/PhoneWindow(29308): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
06-24 15:22:12.550 D/PhoneWindow(29308): *FMB* isFloatingMenuEnabled return false
06-24 15:22:12.600 D/SRIB_DCS(29308): log_dcs ThreadedRenderer::initialize entered! 
06-24 15:22:12.690 I/Timeline(29308): Timeline: Activity_idle id: android.os.BinderProxy@34e35df9 time:16083758
06-24 15:22:14.290 W/paypal.sdk(29308): fg SN:11 PayPal Debug-ID: ef4a37d1b1be8 [sandbox, 2.14.1;release]
06-24 15:22:14.290 E/paypal.sdk(29308): request failure with http statusCode:400,exception:Bad Request
06-24 15:22:14.300 E/paypal.sdk(29308): request failed with server response:{"name":"VALIDATION_ERROR","details":[{"field":"transactions.item_list.items","issue":"Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/#VALIDATION_ERROR","debug_id":"ef4a37d1b1be8"}
06-24 15:22:14.300 E/paypal.sdk(29308): 
06-24 15:22:14.300 E/paypal.sdk(29308): VALIDATION_ERROR
06-24 15:22:14.330 D/PhoneWindow(29308): *FMB* installDecor mIsFloating : true
06-24 15:22:14.330 D/PhoneWindow(29308): *FMB* installDecor flags : 8388610
06-24 15:22:14.330 W/ResourceType(29308): Failure getting entry for 0x01080ad9 (t=7 e=2777) (error -75)
06-24 15:22:14.340 D/ViewRootImpl(29308): Buffer Count from app info with  ::-1 && -1 for :: com.elfo.visionshop from View :: -1 DBQ Enabled ::false false
06-24 15:22:14.350 D/PhoneWindow(29308): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
06-24 15:22:14.350 D/PhoneWindow(29308): *FMB* isFloatingMenuEnabled return false
06-24 15:22:14.380 D/SRIB_DCS(29308): log_dcs ThreadedRenderer::initialize entered! 
06-24 15:22:14.380 E/ViewRootImpl(29308): sendUserActionEvent() mView == null_

Any workaround? :-)

**Comment by fcogutierrez** [comment] 2016-06-30 10:04
@AlejandroRuiz could you reproduce it?

**Comment by kevinleungwork** [comment] 2016-07-25 15:01
![image](https://cloud.githubusercontent.com/assets/19150446/17105871/94b94288-52bb-11e6-8b3f-80c9a47d84ef.png)

Definitely because of decimals - if you use rounded values, payment works. If you use decimals , eg 15.99, the payment fails. I tried using decimal.round(15.99,2) and other conversions but this is definitely occuring at the paypal.forms level.

**Comment by kevinleungwork** [comment] 2016-07-28 02:29
Just wanna check if there are any workarounds for this while this is getting fixed (is it getting fixed ? )?

**Comment by kevinleungwork** [comment] 2016-07-28 02:54
@javiholcman - have you tried using the paypal account (not sandbox) with this? I am going to try the non-sandbox to see if this is happening in the normal paypal accounts (to check if it affects there too). But if you have already tried the normal paypal account, please let us know so that we can cross this test off the list).

**Comment by javiholcman** [comment] 2016-07-28 02:57
Hi @kevinleungwork. No I don't. In my case I don't need to use decimals. We just rounded values. Sorry.

**Comment by kevinleungwork** [comment] 2016-07-28 03:00
@javiholcman - thanks for your prompt reply and sharing your findings :) . I will let you guys know what was my outcome. Sadly, in my case, I have to cover transactions using cents or pennies (hence the issue with decimals).

**Comment by AlejandroRuiz** [comment] 2016-07-28 03:17
@kevinleungwork did you have any code example about your usage and your android device system config, I tried to replicate the @fcogutierrez  and @javiholcman issue using Spanish(Spain) and using EUR and NOK money type and everything is working fine on my side so i need more insights to replicate this issue

**Comment by kevinleungwork** [comment] 2016-07-28 04:14
@AlejandroRuiz - Hello Alejandro, Thank you for your prompt reply. Actually, I have just connected my project with the nuget package (paypal forms 2.06) and I followed:
https://libraries.io/nuget/PayPal.Forms

I initialised with my paypal sandbox id for the app:

global::Xamarin.Forms.Forms.Init ();
 CrossPayPalManager.Init(new PayPalConfiguration(
                    PayPalEnvironment.NoNetwork,
                    "Your PayPal ID from https://developer.paypal.com/developer/applications/"
                    )
                    {
                      //If you want to accept credit cards
                      AcceptCreditCards = true,
                    //Your business name
                      MerchantName = "Test Store",
                      //Your privacy policy Url
                      MerchantPrivacyPolicyUri = "https://www.example.com/privacy",
                      //Your user agreement Url
                      MerchantUserAgreementUri = "https://www.example.com/legal"
                  }
            );

I added:

I reused the paypal tests you used inside a click event:

async void BuyManythingsCustomAddressButton_Clicked(object sender, EventArgs e)
		{
			var result = await CrossPayPalManager.Current.Buy(
				new PayPalItem[] {
					new PayPalItem ("sample item #1", 2, new Decimal (87.50), "HKD", "sku-12345678"),
					new PayPalItem ("free sample item #2", 1, new Decimal (0.00), "HKD", "sku-zero-price"),
					new PayPalItem ("sample item #3 with a longer name", 6, new Decimal (37.99), "HKD", "sku-33333")
				},
				new Decimal(12.55),
				new Decimal(13.20),
				new ShippingAddress("My Custom Recipient Name", "Custom Line 1", "", "My City", "My State", "12345", "MX")
			);
			if (result.Status == PayPalStatus.Cancelled)
			{
				Debug.WriteLine("Cancelled");
			}
			else if (result.Status == PayPalStatus.Error)
			{
				Debug.WriteLine(result.ErrorMessage);
			}
			else if (result.Status == PayPalStatus.Successful)
			{
				Debug.WriteLine(result.ServerResponse.Response.Id);
			}
		}


I changed:
1) USD to HKD (but both USD and HKD throw this error)
2) I just used my paypal sandbox client ID (as no username or password needed by your solution), and the sandbox has been credited to HK$99999
3) FOr my android emulator, I am using android 5 and also used 1gb of memory in my visual studio environment. 

Actually, not many changes to be honest. 

SO what happens when the above code section executes is that I get a paypal sign in, which I can fill in, and then it starts processing, and at that point, it throws the error about the payment not being valid (and it only happens when the total amount sent to paypal has decimal values - for round numbers with no decimals, there are no issues).

**Comment by AlejandroRuiz** [comment] 2016-07-28 15:46
@kevinleungwork which language and country did you have set on your Android device?

**Comment by fcogutierrez** [comment] 2016-07-28 16:10
@AlejandroRuiz here you have a solution with every configured. You will be able to reproduce the decimals issue quickly :-)
[POC.zip](https://github.com/AlejandroRuiz/PayPal.Forms/files/388813/POC.zip)

**Comment by kevinleungwork** [comment] 2016-07-28 16:13
@AlejandroRuiz - Thank you for your help.

I am using English on my android emulator and the country, I checked the locale and it is 'US' on the emulator.

I also just checked and to be precise, the android is 5.1.1.

**Comment by AlejandroRuiz** [comment] 2016-07-28 20:40
@javiholcman @fcogutierrez @kevinleungwork this is now fixed on version which will be available in nuget right now if you get another error please check next link https://github.com/paypal/PayPal-Android-SDK/search?q=request+failure+with+http+statusCode%3A422%2Cexception%3AUnprocessable+Entity&type=Issues&utf8=✓ this happen due a misconfigured Paypal sandbox-live user account please close the ticket if your issue is now solved

**Closed** 2016-07-29 02:54 UTC
Labels: bug

**Comment by fcogutierrez** [comment] 2016-07-29 10:28
Hi @AlejandroRuiz.

First of all, THANKS A LOT for your work :)

I updated the library but I get this message:

07-29 11:34:21.315 E/paypal.sdk(31350): request failure with http statusCode:422,exception:Unprocessable Entity
07-29 11:34:21.315 E/paypal.sdk(31350): request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"fd2957722489d","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

**Comment by AlejandroRuiz** [comment] 2016-07-29 12:10
Please read my previous notes

**Comment by fcogutierrez** [comment] 2016-07-29 13:10
@AlejandroRuiz  I already read your notes and visited the link but I do not see any helpful there...

**Comment by AlejandroRuiz** [comment] 2016-07-29 13:19
@fcogutierrez as the Paypal guys said in that threads that issue is related with a differents types of issues if you want to test it successfully use USD instead of NDK , wait until the Paypal guys give you information related of your debug_id or try creating a new sandbox config

**Comment by fcogutierrez** [comment] 2016-07-29 13:49
Strange, but with "USD" instead of "NOK" it works perfectly... :S

**Comment by kevinleungwork** [comment] 2016-07-29 17:30
Thanks a lot for your help and quick response @AlejandroRuiz .

However, for me, I am still facing an issue
Trying this code for a payment in the sandbox:
protected async void performPayment()
        {
            var result = await CrossPayPalManager.Current.Buy(new PayPalItem[] {
                new PayPalItem ("sample item #1", 2, new Decimal (87.50), "USD",
                    "sku-12345678"),
                new PayPalItem ("free sample item #2", 1, new Decimal (0.00),
                    "USD", "sku-zero-price"),
                new PayPalItem ("sample item #3 with a longer name", 6, new Decimal (37.99),
                    "USD", "sku-33333")
            }, new Decimal(20.5), new Decimal(13.20));
            if (result.Status == PayPalStatus.Cancelled)
            {
                //Debug.WriteLine("Cancelled");
            }
            else if (result.Status == PayPalStatus.Error)
            {
                //Debug.WriteLine(result.ErrorMessage);
            }
            else if (result.Status == PayPalStatus.Successful)
            {
                //Debug.WriteLine(result.ServerResponse.Response.Id);
            }
        }

this now returns this error:
![image](https://cloud.githubusercontent.com/assets/19150446/17257533/130a8700-55f5-11e6-9375-de861c796164.png)


I researched about this error, and it mentions that .Net 4.6 made a change to this function (currently, I am still on .Net 4.5 in my project). I need to test further on this...

**Comment by AlejandroRuiz** [comment] 2016-07-29 21:23
I'll check in a free time on VS/Win since im using XS/Mac

**Comment by kevinleungwork** [comment] 2016-07-30 01:25
@AlejandroRuiz - thank you for your kind help. Greatly appreciate it :-). I will keep checking what is wrong on my end too, and share any findings.

**Comment by kevinleungwork** [comment] 2016-07-30 15:09
Hi @AlejandroRuiz , I found that the error occurs in :+1:  var result = await CrossPayPalManager.Current.Buy(new PayPalItem[] {
                new PayPalItem ("sample item #1", 2, new Decimal (87.50), "USD",
                    "sku-12345678"),
                new PayPalItem ("free sample item #2", 1, new Decimal (0.00),
                    "USD", "sku-zero-price"),
                new PayPalItem ("sample item #3 with a longer name", 6, new Decimal (37.99),
                    "USD", "sku-33333")
            }, new Decimal(20.5), new Decimal(13.20));

The 'String.Format not found' occurs there (before even logging to Paypal - the error in version 2.06 allowed the login to paypal first and then threw 'payment information is invalid' , but in this new version, the error 'String.Format not found' occurs before the paypal login and just after triggering the 'CrossPayPalManager.Current.Buy' method.

I hope this helps. I am using visual studio 2015 and xamarin on that environment, on a windows machine (it is not ideal and visual studio has been slowing degrading in quality), but it would still be nice to have it working on visual studio.

Thanks for your help!

**Comment by kevinleungwork** [comment] 2016-07-31 14:27
@AlejandroRuiz - I have repaired my vs (because I suspected the String.Format issue seemed to originate from the native libraries) and xamarin and it is now working. It seems my vs installation had a slight issue.

Thanks a lot for your help and this great component! I will continue to test it and share any issues here if any.

**Comment by sureshtest** [comment] 2017-04-24 06:01
hey Guys This Thread is very useful for me. and i am asking one question i am not getting any return success message or any return values from PayPal in xamarin forms. here PayPal logging in then payment after payment not getting any success message.

 i am using the PayPal configuration like this(below code)

var result = await CrossPayPalManager.Current.Buy(new PayPalItem("Test Product", new Decimal(12.50), "USD"), new Decimal(150.30));
                    if (result.Status == PayPalStatus.Cancelled)
                   {
                       Debug.WriteLine("Cancelled");
                   }
                   else if (result.Status == PayPalStatus.Error)
                   {
                       Debug.WriteLine(result.ErrorMessage);
                   }
                   else if (result.Status == PayPalStatus.Successful)
                   {
                       Debug.WriteLine(result.ServerResponse.Response.Id);
                   }
Thanks in Advance

**Comment by AlejandroRuiz** [comment] 2017-04-24 14:51
@sureshtest what is the Environment that you have, also provide a console output about your issue and if there a new issue please create another ticket for that, don't put any not-related data for tickets

**Comment by amitkumar15** [comment] 2018-07-31 11:37
Hi @AlejandroRuiz After completion of payment balance is not increasing of my merchant account.But Status Always come success . I sent my App client Id in PayPalConfiguration under your paypald is this correct ?
